**session 5**  
1401/06/15  

In [71]:
import numpy as np
x = np.random.randint(100, size=(2,3,4)) 
print(x)
print(type(x))

[[[96 58 60 36]
  [79 39 13 57]
  [98 14 42 97]]

 [[13 44  5  0]
  [ 9 96 77 41]
  [50 67 12  7]]]
<class 'numpy.ndarray'>


In [114]:
from numpy import random
x = random.randint(201,size=(4))
# random.rand() --> float number 0 - 1
print(x-100) #[-100,100]

[ 40 -41 -91 -88]


In [120]:
import numpy.random as rd
ls = [1,2,"apple", "sun", 3.4]
x = rd.choice(ls,size=(10,2))
print(x)

[['sun' '2']
 ['2' '1']
 ['sun' '1']
 ['1' '1']
 ['apple' '1']
 ['apple' 'sun']
 ['1' '3.4']
 ['sun' '3.4']
 ['1' 'apple']
 ['sun' '1']]


In [124]:
from numpy import array as arr
x = arr([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [131]:
y = arr([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(y)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
