**session 6**  
*1401/06/22*  
*numpy / matplotlib*

In [9]:
import numpy as np

''' m1 =   1
           2
           3

    m2 =   1   2   3
'''
m1 = np.array(([1,2,3],[4,5,6]))
m2 = np.array(([7,8],[9,10],[11,12]))

print(m1,'\n')
print(m2,'\n')

m3 = np.dot(m1,m2)
print(2*m1,'\n')
print(m3)

[[1 2 3]
 [4 5 6]] 

[[ 7  8]
 [ 9 10]
 [11 12]] 

[[ 2  4  6]
 [ 8 10 12]] 

[[ 58  64]
 [139 154]]
